/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jForm;

import control.QuanLyDangKy;
import control.QuanLyThongTinXe;
import control.QuanLyUser;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.DangKiBienSo;
import model.ThongTinXe;
import model.User;

/**
 *
 * @author ADMIN
 */
public class ThanhToanFrame extends javax.swing.JFrame {

    /**
     * Creates new form in
     */
    
    DangKiBienSo dangKiBienSo;
    QuanLyDangKy quanLyDangKy;
    QuanLyThongTinXe quanLyThongTinXe;
    QuanLyUser quanLyUser;
    public ThanhToanFrame() {
        initComponents();
        getContentPane().setBackground(new Color(220,220,220));
    }
   
   public ThanhToanFrame(DangKiBienSo dangKi) {
        initComponents();
        quanLyDangKy=new QuanLyDangKy();
        quanLyUser = new QuanLyUser();
        quanLyThongTinXe = new QuanLyThongTinXe();
        getContentPane().setBackground(new Color(220,220,220));
        
        //set thông tin xe
        txtTenchuxe.setText("Mã xe : "+ dangKi.getTenChuXe());
        txtNamsinh.setText("Năm sinh: "+ dangKi.getNamsinh());
        txtDiachi.setText("Địa chỉ: "+ dangKi.getDiaChi());
        txtCccdchuxe.setText("CCCD chủ xe: "+ dangKi.getCccdChuXe());
        txtSohoadondientu.setText("Số hoá đơn điện tử: "+ dangKi.getSoHoaDonDienTu());
        txtMaSoThue.setText("Mã số thuế: "+ dangKi.getMaSoThue());
        txtMahosokhai.setText("Mã hồ sơ khai lệ phí trước bạ: "+ dangKi.getMaHoSoKhaiLePhiTruocBa());
        txtSoToKhai.setText("Số tờ khai hải quân: "+ dangKi.getSoToKhaiHaiQuan());
        txtSoSeri.setText("Số Seri KTCLXX: "+ dangKi.getSoSeriKTCLXX());
        txtGmail.setText("Gmail: "+ dangKi.getGmailChuXe());
        txtBienSoXe.setText("43A - " + dangKi.getBienSoXe());
        
        User userdanglam = new User();
        userdanglam= quanLyUser.getUserById(dangKi.getIdAccountDuyet());
        String hotennv=userdanglam.getHoVaTen();
        String tennhanvien=hotennv.substring(hotennv.lastIndexOf(" "), hotennv.length());

        txttennhanvien.setText(hotennv);
        txtchuki.setText(tennhanvien);
        
        ThongTinXe ttxdanglam = new ThongTinXe();
        ttxdanglam = quanLyThongTinXe.getTTXById(dangKi.getIdThongTinXeNo());
        if(ttxdanglam.getIdLoaiXeNo().equals("LX001"))
            txtTenloaixe.setText("Tên loại xe: Xe máy");
        if(ttxdanglam.getIdLoaiXeNo().equals("LX002"))
            txtTenloaixe.setText("Tên loại xe: Xe ô tô");
        if(ttxdanglam.getIdLoaiXeNo().equals("LX003"))
            txtTenloaixe.setText("Tên loại xe: Xe mô tô");
        if(ttxdanglam.getIdLoaiXeNo().equals("LX004"))
            txtTenloaixe.setText("Tên loại xe: Xe bus");
        txtMauson.setText("Màu sơn: " + ttxdanglam.getMauSon());
        txtNhanHieu.setText("Nhãn hiệu: " +ttxdanglam.getNhanHieu());
        txtSoLoai.setText("Số loại: " + ttxdanglam.getSoLoai());
        if(ttxdanglam.getTheLoaiDangKi().equals("1"))
            txtTinhTrangDangKi.setText("Tình trạng đăng kí: Đăng kí mới");
        if(ttxdanglam.getTheLoaiDangKi().equals("1"))
            txtTinhTrangDangKi.setText("Tình trạng đăng kí: Đăng kí sang tên");
        if(ttxdanglam.getTheLoaiDangKi().equals("1"))
            txtTinhTrangDangKi.setText("Tình trạng đăng kí: Đăng kí tạm thời");
        if(ttxdanglam.getTheLoaiDangKi().equals("1"))
            txtTinhTrangDangKi.setText("Tình trạng đăng kí: Cấp lại biển số");
        
        User NLTT = new User();
        NLTT = quanLyUser.getUserById(dangKi.getIdAccountDangKi());
        txtTenNLTT.setText("Người làm thủ tục: "+NLTT.getHoVaTen());
        txtCccdNLTT.setText("CCCD người làm thủ tục: " + NLTT.getCccd());
    }
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        pnbienlai = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtTenchuxe = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JLabel();
        txtNamsinh = new javax.swing.JLabel();
        txtSohoadondientu = new javax.swing.JLabel();
        txtMaSoThue = new javax.swing.JLabel();
        txtMahosokhai = new javax.swing.JLabel();
        txtSoToKhai = new javax.swing.JLabel();
        txtSoSeri = new javax.swing.JLabel();
        txtBienSoXe = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txttennhanvien = new javax.swing.JLabel();
        txtchuki = new javax.swing.JLabel();
        txtCccdchuxe = new javax.swing.JLabel();
        txtGmail = new javax.swing.JLabel();
        txtTinhTrangDangKi = new javax.swing.JLabel();
        txtTenloaixe = new javax.swing.JLabel();
        txtMauson = new javax.swing.JLabel();
        txtNhanHieu = new javax.swing.JLabel();
        txtSoLoai = new javax.swing.JLabel();
        txtTheLoaiDangKi = new javax.swing.JLabel();
        txtTenNLTT = new javax.swing.JLabel();
        txtCccdNLTT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btthoat = new javax.swing.JButton();

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnbienlai.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ĐƠN ĐĂNG KÍ");

        txtTenchuxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenchuxe.setText("Tên chủ xe:");
        txtTenchuxe.setToolTipText("");

        txtDiachi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDiachi.setText("Địa chỉ:");
        txtDiachi.setToolTipText("");

        txtNamsinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNamsinh.setText("Năm sinh:");
        txtNamsinh.setToolTipText("");

        txtSohoadondientu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSohoadondientu.setText("Số hoá đơn điện tử:");
        txtSohoadondientu.setToolTipText("");

        txtMaSoThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSoThue.setText("Mã số thuế:");
        txtMaSoThue.setToolTipText("");

        txtMahosokhai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMahosokhai.setText("Mã hồ sơ khai lệ phí trước bạ:");
        txtMahosokhai.setToolTipText("");

        txtSoToKhai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoToKhai.setText("Số tờ khai hải quân:");
        txtSoToKhai.setToolTipText("");

        txtSoSeri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoSeri.setText("Số Seri KTCLXX:");
        txtSoSeri.setToolTipText("");

        txtBienSoXe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBienSoXe.setText("Biển số xe:");
        txtBienSoXe.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Người duyệt:");
        jLabel17.setToolTipText("");

        txttennhanvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttennhanvien.setText("Nguyễn Trí Đức");
        txttennhanvien.setToolTipText("");

        txtchuki.setFont(new java.awt.Font("Blackadder ITC", 0, 24)); // NOI18N
        txtchuki.setText("Duc");

        txtCccdchuxe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCccdchuxe.setText("CCCD chủ xe:");
        txtCccdchuxe.setToolTipText("");

        txtGmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGmail.setText("Gmail chủ xe:");
        txtGmail.setToolTipText("");

        txtTinhTrangDangKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTinhTrangDangKi.setText("Tình trạng đăng kí: Đã Duyệt");
        txtTinhTrangDangKi.setToolTipText("");

        txtTenloaixe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenloaixe.setText("Tên loại xe:");
        txtTenloaixe.setToolTipText("");

        txtMauson.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMauson.setText("Màu sơn:");
        txtMauson.setToolTipText("");

        txtNhanHieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNhanHieu.setText("Nhãn hiệu:");
        txtNhanHieu.setToolTipText("");

        txtSoLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSoLoai.setText("Số loại:");
        txtSoLoai.setToolTipText("");

        txtTheLoaiDangKi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTheLoaiDangKi.setText("Thể loại đăng kí:");
        txtTheLoaiDangKi.setToolTipText("");

        txtTenNLTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenNLTT.setText("NLTT");
        txtTenNLTT.setToolTipText("");

        txtCccdNLTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCccdNLTT.setText("CCCD NLTT:");
        txtCccdNLTT.setToolTipText("");

        javax.swing.GroupLayout pnbienlaiLayout = new javax.swing.GroupLayout(pnbienlai);
        pnbienlai.setLayout(pnbienlaiLayout);
        pnbienlaiLayout.setHorizontalGroup(
            pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbienlaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnbienlaiLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbienlaiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
            .addGroup(pnbienlaiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBienSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTinhTrangDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCccdchuxe, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtGmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoSeri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                    .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTenchuxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addComponent(txtNamsinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMahosokhai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addComponent(txtSohoadondientu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaSoThue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtSoToKhai, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMauson, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhanHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheLoaiDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCccdNLTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                        .addComponent(txtTenNLTT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbienlaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnbienlaiLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtchuki, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnbienlaiLayout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbienlaiLayout.createSequentialGroup()
                        .addComponent(txttennhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        pnbienlaiLayout.setVerticalGroup(
            pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnbienlaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnbienlaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnbienlaiLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenloaixe)
                        .addGap(14, 14, 14)
                        .addComponent(txtMauson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhanHieu)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoLoai)
                        .addGap(18, 18, 18)
                        .addComponent(txtTheLoaiDangKi)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenNLTT)
                        .addGap(18, 18, 18)
                        .addComponent(txtCccdNLTT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnbienlaiLayout.createSequentialGroup()
                        .addComponent(txtTenchuxe)
                        .addGap(12, 12, 12)
                        .addComponent(txtNamsinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiachi)
                        .addGap(18, 18, 18)
                        .addComponent(txtCccdchuxe)
                        .addGap(12, 12, 12)
                        .addComponent(txtSohoadondientu)
                        .addGap(19, 19, 19)
                        .addComponent(txtMaSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMahosokhai)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoToKhai)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoSeri)
                        .addGap(18, 18, 18)
                        .addComponent(txtGmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtTinhTrangDangKi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBienSoXe)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtchuki, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttennhanvien)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG KÍ BIỂN SỐ XE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID Đăng kí:");

        jButton1.setBackground(new java.awt.Color(51, 253, 15));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jButton1.setText("In hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(220, 220, 220));

        btthoat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btthoat.setText("x");
        btthoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btthoat.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btthoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btthoatMouseExited(evt);
            }
        });
        btthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btthoat, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnbienlai, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(20, 20, 20))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnbienlai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(isAlwaysOnTop())
            setAlwaysOnTop(false);
        printRecord(pnbienlai);
        setAlwaysOnTop(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthoatActionPerformed
        // TODO add your handling code here:\
        this.dispose();
    }//GEN-LAST:event_btthoatActionPerformed

    private void btthoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthoatMouseEntered
        // TODO add your handling code here:
        btthoat.setBackground(Color.red);
        btthoat.setForeground(Color.white);
    }//GEN-LAST:event_btthoatMouseEntered

    private void btthoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthoatMouseExited
        // TODO add your handling code here:
        btthoat.setBackground(Color.white);
        btthoat.setForeground(Color.black);
    }//GEN-LAST:event_btthoatMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new In().setVisible(true);
//            }
//        });
//    }
    
    public void printRecord(JPanel panel){
        PrinterJob printerJob=PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print");
        // Set Printable
        printerJob.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics,PageFormat pageFormat,int pageIndex) throws PrinterException{
            // Check If No Printable Content
                if(pageIndex>0)
                {
                    return Printable.NO_SUCH_PAGE;
                }

                // Make 2D Graphics to map content
                Graphics2D graphics2D=(Graphics2D)graphics;
                // Set Graphics Translations
                graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
                // This isapage scale.Default should be 0.3 I am using 0.5
                graphics2D.scale(1.1,1.1);
                // Now paint panel as graphics2D
                panel.paint(graphics2D);
                // return if page exists
                return Printable.PAGE_EXISTS;
                
            }
        });
        // Store printerDialog as boolean
        boolean returningResult=printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
        // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
            }
            catch(PrinterException printerException){
            JOptionPane.showMessageDialog(this,"Print Error:"+printerException.getMessage());
            }
        }
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btthoat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel pnbienlai;
    private javax.swing.JLabel txtBienSoXe;
    private javax.swing.JLabel txtCccdNLTT;
    private javax.swing.JLabel txtCccdchuxe;
    private javax.swing.JLabel txtDiachi;
    private javax.swing.JLabel txtGmail;
    private javax.swing.JLabel txtMaSoThue;
    private javax.swing.JLabel txtMahosokhai;
    private javax.swing.JLabel txtMauson;
    private javax.swing.JLabel txtNamsinh;
    private javax.swing.JLabel txtNhanHieu;
    private javax.swing.JLabel txtSoLoai;
    private javax.swing.JLabel txtSoSeri;
    private javax.swing.JLabel txtSoToKhai;
    private javax.swing.JLabel txtSohoadondientu;
    private javax.swing.JLabel txtTenNLTT;
    private javax.swing.JLabel txtTenchuxe;
    private javax.swing.JLabel txtTenloaixe;
    private javax.swing.JLabel txtTheLoaiDangKi;
    private javax.swing.JLabel txtTinhTrangDangKi;
    private javax.swing.JLabel txtchuki;
    private javax.swing.JLabel txttennhanvien;
    // End of variables declaration//GEN-END:variables
}
